# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20181228_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='kirr_url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='click', to='shortener.KirrURL'),
        ),
    ]
